Invoke onSuccess and onFailure handlers properly for async methods
palantir/tritium pull request #181
Opened 2019-02-06 18:29 UTC by ellisjoe

2019-02-06 18:32 UTC, cakofony commented on tritium-lib/src/test/java/com/palantir/tritium/proxy/InvocationEventProxyTest.java
> +    }
Did you intend to commit this?

2019-02-06 18:33 UTC, ellisjoe commented on tritium-lib/src/test/java/com/palantir/tritium/proxy/InvocationEventProxyTest.java
> +    }
haha nope. removed :)

2019-02-06 18:43 UTC, carterkozak requested changes
I think this will break tracing-java and any other handler which sets and removes thread-local state. We need some way to opt into asynchronous callbacks to avoid breaking existing implementations.

There's a separate related conversation around how we want to support tracing-java for asynchronous operations.

2019-02-06 18:43 UTC, cakofony commented on tritium-lib/src/main/java/com/palantir/tritium/proxy/InvocationEventProxy.java
> +        } else if (result instanceof CompletableFuture) {
Should use `CompletionStage` over `CompletableFuture`

2019-02-06 22:37 UTC, ellisjoe commented
@cakofony cool. Let's find some time to work through the current issues and what a better solution would look like

2019-02-08 15:05 UTC, cakofony commented on tritium-core/src/main/java/com/palantir/tritium/event/CompositeInvocationEventHandler.java
> +        return true;
Tritium bundles all handlers together using the composite handler, I think this will disable async support if the tracing handler is enabled.

2019-02-08 15:07 UTC, cakofony commented on tritium-lib/src/main/java/com/palantir/tritium/proxy/InvocationEventProxy.java
> +                    && (eventHandler.asyncSupport() || !isAsync(method));
I think we want to remove this line. Tracing doesn't support async operations, but the tracing thread state is passed to executors, which will provide valuable information.

2019-02-08 15:11 UTC, cakofony commented on tritium-core/src/main/java/com/palantir/tritium/event/CompositeInvocationEventHandler.java
> +        return true;
I not sure CompositeInvocationEventHandler is the right abstraction for InvocationEventProxy any longer given this change.

2019-02-08 15:37 UTC, schlosna commented
@ellisjoe @cakofony interested in your thoughts on the following questions:

- What async return types do we want to support?
    - `CompletionStage` / `CompletableFuture`
    - `ListenableFuture`
    - `Future`?
    - `InputStream`?
    - [`ClosableIterator`](https://github.com/palantir/atlasdb/blob/develop/atlasdb-commons/src/main/java/com/palantir/common/base/ClosableIterator.java)?
- What do we want the semantics to be if some registered handlers support async, while others do not?
- Do we want to capture anything to indicate completion (success/failure) for the instrumented method itself before/after the async completion?

2019-02-08 15:54 UTC, cakofony commented
I can imagine requests for https://projectreactor.io and http://reactivex.io types. Perhaps we should provide special handling for retrofit in conjure-java-runtime without making changes to tritium.

> What do we want the semantics to be if some registered handlers support async, while others do not?

All handlers are expected be invoked as though they're the only handler registered, regardless of configuration. We shouldn't change this.

2019-02-11 14:28 UTC, ellisjoe commented
Hey so I'm gonna have to punt on working through the rest of the changes here. At the end of the day it doesn't actually fix my issue which is that I need tracing to support async invocations so I'm gonna close this for now and can come back later or someone else can feel free to pick it up.

2019-02-11 14:28 UTC, closed without merging